### ISSUE TITLE
Tool reports error 'Unsupported file type' when using on .net readytorun executables

### ISSUE THREAD

**Issue by tapika** [runestubbe/Crinkler#10]
Download choco.exe from here:
https://github.com/tapika/swupd/releases

Try to compress using Crinkler.

Tool informs `Unsupported file type` when using on it.

**Comment by runestubbe** [comment]
Crinkler is not an ordinary executable file compressor. It takes object files instead of executables as input. It is also specialized for tiny executables on the order of 1-4KB. The choco.exe executable you linked is 65.9MB, which is just not going to work with Crinkler.

Maybe something like UPX would better suit your needs. Compressed executables are more likely to be considered suspicious by various antivirus systems, so it is also worth considering if saving a few MB is really worth that headache.
